language: java
script: ./gradlew compileDocker
notifications:
  hipchat:
    rooms:
      secure: bgc0fi63YRtkbpXT4wEkFuid10kkc59KJrBw2x6CZ7jVz4dRkKv7pDzcFdyWJcqy0+ud8hDTtEJy89pCCnjMsW0s1HAmcT28cyj+Np2xlDLuX6nYs/Hnbu9c0uOH+khc12WrHX2u6VsW+tnsdXU727phmj9SpGl1nwZ+T4+N+bbsZJyFhTPSuPPMjz7pwQN/F8Ad2/1LMHI3gUGSAyTKBPEFnB5aV5eiUc9Z2970AAIDoSUaR6niKGoQoHydVM68rFi3qvYm3/WaoBM6E8zI6+5uiVplNgvMLeEbeQBzABYox1LnW2XkN1VHktVz23Yt1CvtA0iVkJUmnjgSLFL3B5DZ8QLUT8S0qk8j5rrd9rfgZcuZ0SGLfjkfZ1P2gePLl28WZaoEG3h9QNG1TTjvUziqoWrt9FFy0t54e/EYeY7iheCWcUJVoAQRulSxbQFboUzHX7yA5GYcktQXHa9gP8xAPSrMzm54hFiRJwaftz+O372ONvsTFqEhr4BcIFltv/UHsDnM+hErvjBiHVcQVZuGdwbIZS/3AewFGYrQ6qsXdQEOEe94aBzBYsVX+C2IGZM09G1OK4v7dFB/62Uleg7ZeWrmwejDB/1QLjV7rzr/txpVBjXzNLkAv+72927l9j0Nn3Lv2aSweVurEZbN+c6SdUPRg4jWY+sFlUS1yhM=
deploy:
  provider: releases
  api_key:
    secure: haYPr7vdwDx2LU+vVnaT81mvQYUsPoaOnvdVGnMgV17oHAvgdvoB1Rm/uPB4fzA1b7xaQ3/LaSzZIjeT0PhEtit55RO72l3cq0YUPD0dMMxRQp4z3vlM2LT6vl5d+U80tvtWzZ+C/q1E4KcpdCLDWs/yN6CNbUXYGWvU+q1urxrZZsXA0FRcOu1HJj42kqJPO5FwapJMeHDYOSZtxCMZHN4jh355wpGncdzYRrm77EcS6mJZRS+kRvWF+OdldEhmhkXyvX2qT4XPi9qoITuk5fF0XirwU07Mhslh7UvMuju1TxYJAFaWCpPLTjnrkR3pIYvSIF6nmJkRTFsggvuKu4SOXLWEsEZTVkf4XwIocetCKL0yJ5KshLwLcMOUVnXbtVgo+V20QspWre5orR9hOMmNhZbKCxmTyXb/Q3cjP+kkhR+53zGTBe2FaPgeGikWgVdz6nHbPQeq5JbK+IleyPIJvYGNztX6iUSHlJeLCn7QSvtfUGMMgjZmez2gLEIfog8wKOaauwmD+tAKCnINVqY0VoqQzrcSgm5IHDkFRX1g9i/GeZRaEECDxDHAX/cAuydik/VTe3SJ2GYbhCkIDmCeA31B2D9IiSUWudqEZR2U2y/Y5i8t1nhWkBOen9X5i/QwOrvxlGsSx/CJx+SGezQF0OxeqZ5Gtdur/CGg/iY=
  file: ./build/libs/xld-personal-credentials-plugin-5.0.0.jar
  on:
    all_branches: true
    tags: true
